import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import HeaderApp from './components/header.page'
import 'bootstrap/dist/css/bootstrap.min.css';
import { Container } from 'react-bootstrap';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderApp/>
        <Container>{children}</Container>
        <ToastContainer />
      </body>
    </html>
  )
}
